### ISSUE TITLE
Wo sind die alten Commits?

### ISSUE THREAD

**Issue by kangalioo** [nerrixDE/DSBApi#1]
Ich hatte heute morgen hier vorbeigeschaut, und mir den Commit zur Version 0.0.2 angeschaut. Jetzt sind die alten Commits plötzlich nicht mehr da. Könntest du die irgendwie wiederherstellen?

Bei dem 0.0.2 Commit hatte jemand einen interessanten Kommentar gemacht den ich mir eig. noch mal anschauen wollte

**Comment by nerrixDE** [comment]
Ich habe die Commits leider überschrieben, mein git-Client war falsch eingestellt.
Ich kann den jetzt auch nicht restoren, aber ich kann sagen, dass in dem Kommentar bei Verstion 0.0.2 geschrieben war, dass die der Web-API-Endpoint (`https://www.dsbmobile.de/jhw-1fd98248-440c-4283-bef6-dc82fe769b61.ashx/GetData`) eine Konstante ist. `jhw...` ändert sich nicht, auch bei anderen Credentials nicht.

**Comment by kangalioo** [comment]
> Web-API-Endpoint (https://www.dsbmobile.de/jhw-1fd98248-440c-4283-bef6-dc82fe769b61.ashx/GetData) eine Konstante ist. jhw... ändert sich nicht, auch bei anderen Credentials nicht.

Ah genau das hatte ich gesucht, danke.

**Comment by nerrixDE** [comment]
Die URL habe ich einfach durch Network Monitoring herausgefunden

**Comment by kangalioo** [comment]
Ja ich auch, und ich dachte sie sei konstant, bis es irgendwann nicht mehr ging mit der URL. Also habe ich nochmal im Browser geguckt, welche URL denn nun angefragt wird, und da war es eine andere.
Also, ändert sich die URL (Jetzt gerade geht übrigens wieder nur die ursprüngliche URL)

Ich würde gerne wissen, wonach sich die Daten URL der Desktop-API richtet, damit ich mit der Desktop-API verlässlich kommunizieren kann.
