### ISSUE TITLE
TypeError: the JSON object must be str, not 'bytes'

### ISSUE THREAD

**Issue by brainoc** [nerrixDE/DSBApi#12]
Ich bekomme bei der Ausführung leider den folgenden Fehler:
python3 dsb2.py
Traceback (most recent call last):
  File "dsb2.py", line 4, in <module>
    entries = dsbclient.fetch_entries() # Rückgabe einer JSON Liste an Arrays
  File "/home/pi/.local/lib/python3.5/site-packages/dsbapi/__init__.py", line 45, in fetch_entries
    data_compressed = json.loads(timetable_data.content)["d"]
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

**Comment by brainoc** [comment]
-----BEGIN PGP MESSAGE-----
Version: Keybase OpenPGP v2.1.3
Comment: https://keybase.io/crypto

wcBMA2Y76++sMEu0AQf+MMRCLXdigu2+b/9/1gE2agEgsO4R9OVAF7bcU+qa8e80
yDOFOH9HHDaLUa8sb1y37P6A912ehqV3RS175CTY7IHbN3ZNiRnfaWCUcymomTFP
M/Ivo7U8sHJr2TSQ74O1YVqfWdSMLFsxzQItKn8EVfNd6nBem7Yo5CRVH4MmAI3z
OaCx/DWGhYlpA+fJzw6OfjwMowekTzh4rzTJxBVLQrl59ZKrDAcZVPGNdqIU03Rm
8JvNNMexRTClsejWZV9eF+KwimfwnKDi5FVN6VNwguxwNZpt7ApFRil4mucGT7aM
gUPe3On4u7bXHqYrT6/NsUqhogcOeCA5x3YkMS7cotJlAekDPZnU6v3068Ud4/te
zuIfEkLy8NOV9Ehs61/JYIMjW6KLmiOJ4h6lNzbFtbgYUHev+z5calnIHSg7Xe/k
2megCM6PyWeixhYc2hveLAkgsturVWHZiB6h5V56vWLurrKK0Wg=
=m8aQ
-----END PGP MESSAGE-----

**Comment by nerrixDE** [comment]
Unfortunately, I can't reproduce your issue with my credentials.
Can you post your credentials here (https://keybase.io/encrypt#nerrix_de) and then send the encrypted message here - then I can take a look at it.

**Comment by nerrixDE** [comment]
Okay, as I see the integration for multiple plans isn't working. I'm on it.

**Comment by nerrixDE** [comment]
Okay, I took a quick look at it and it seems like your organisation only provides image-based data. Unfortunately we can't parse such data as we do with HTML-tables. Therefore it's not working.
