### ISSUE TITLE
Reihenfolge der Felder geändert?

### ISSUE THREAD

**Issue by cybcon** [nerrixDE/DSBApi#17]
Hi,
aktuell bin ich am implementieren Eurer Bibliothek und mir ist dabei aufgefallen, dass bei uns in der Schule die Felder eine andere Reihenfolge haben.

![Screenshot 2021-04-21 110957](https://user-images.githubusercontent.com/42999275/115528219-23886b80-a292-11eb-8efc-ede4ca80c941.png)

Da ich das Ergebnis in einen Pandas DataFrame lutsche, habe ich als Workaround einfach die Spaltennamen getauscht.
Wenn die Tabellen Überschriften einheitlich sind, könnte man evtl. ein dynamisches Feldnamen mapping einbauen. Leider fehlt mir hier die Vergleichsmöglichkeit.

Viele Grüße,
Micha

**Comment by nerrixDE** [comment]
Ja, jede Schule braut da leider ihren eigenen Brei.

**Comment by cybcon** [comment]
War ja klar :-D

wäre es eine Idee, statt dem `entries.pop(0)` in Zeile 87 einen Parser zu bauen, der ein Array aufbaut z.B. `fields=list()`, die erste Zeile parsed und "normalisiert" und dann den Feldnamen von dort holt?
Man hätte dann auch gleich die Läge der Tabelle, könnte durch die fields loopen und das jeweilige value aus der gerade aktuellen Zeile ermitteln. Dann wären die Namen dann nicht mehr "eindeutig" und in "einfachem Englisch" aber dafür dynamisch und passend zur Schule.

**Comment by cybcon** [comment]
Hab nen Docker container daruas gebaut der das Ding per Pushover verschickt.
https://hub.docker.com/repository/docker/oitc/dsb2pushover

Mal schauen ob ich das mit den dynmischen Tabellen ggf. konfigurativ hinbekomme.

**Comment by nerrixDE** [comment]
👍

**Comment by cybcon** [comment]
Siehe neuen Pull request
