### ISSUE TITLE
GZIP compression / base64 broke

### ISSUE THREAD

**Issue by nerrixDE** [nerrixDE/DSBApi#9]
The compression of the request is different as done in the App, therefore the Server rejects requests made by the API.

**Comment by kangalioo** [comment]
Is that the reason for this crash?
```Traceback (most recent call last):
  File "main.py", line 154, in <module>
    for a in getNews(username, password):
  File "main.py", line 96, in getNews
    doc = getDoc(username, password)
  File "main.py", line 44, in getDoc
    url = getURL(username, password)
  File "main.py", line 93, in getURL
    raise e_android
  File "main.py", line 90, in getURL
    return(myDSB.fetch_entries())
  File "/home/kangalioo/dev/python/Vertretungsplangak_Bot/dsbapi.py", line 50, in fetch_entries
    for page in data["ResultMenuItems"][0]["Childs"]:
IndexError: list index out of range
```

**Comment by nerrixDE** [comment]
@kangalioo No, it's the result. I'll take a look at the issue again today, but it's definitly because of the request's compression is different and therefore invalid.

**Comment by kangalioo** [comment]
By the way what tool are you using to monitor Network traffic on Android? I'd be interested to help find the compression algorithm currently used. I have tried two HTTP capturing apps already but had problems with them

**Comment by jjakobh** [comment]
Are you sure the compression isn't working?
`gzip+base64` works fine for us: https://gitlab.com/jjakobh/dsbserver/blob/master/dsbapi/dsbapi/dsb.py#L48.

Try changing the OsVersion to 27 8.1.0, That worked for us.

**Comment by nerrixDE** [comment]
@kangalioo avd + burp
@jjakobh The Android request contains the Version number as it is in the code rn, but I was able to Insert the b64 string generated by Android into this project's request and it works. I'll investigate it today.

**Comment by nerrixDE** [comment]
What I can say that the reason is definitly found in the compression, Android works with the Version number we use

**Comment by nerrixDE** [comment]
From what I notice Heinekenmedia often changes their endpoint, the only explanation is that they are aware of such APIs and they want to disable them. I made more than 8 adjustments to code, which worked before. This would also explain the breakpoint in webbrowsers debuggers and the newly obfuscated configuration.js file.
The Android App was updated in 2016, so to ensure long-term stability the request must be exactly like the one made by the Android app. I would therefore refuse to adjust the os Version number to a different one, as we aim to emulate one device (in this case a samsung one) !exactly!

To solve our bug I'll adjust the compression today so the result fit's to the one generated by Android.

**Comment by nerrixDE** [comment]
@kangalioo avd + burp
As I see they may validate version numers together with the device model, this is new and broke out codebase, thank you for this hint @jjakobh.
But the encoded base64+gzip is still different than the one generated by Android, so we have to adjust this too as this might be the next thing which will break.
Heinekenmedia broke our API multiple times and they also added the breakpoint in debugger, obfuscated configuration.js, etc..
The request must be exactly the same as the one by the android app, this is the only way to make this project stable... until the next android update (but the last one was 2016 c:)
